# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evaluate standard normal cdf for matrix of variates
#' 
#' @param m A matrix of variates 
pnorm_mat <- function(m) {
    .Call('_varapproxr_pnorm_mat', PACKAGE = 'varapproxr', m)
}

#' Evaluate standard normal density for matrix of variates
#' 
#' @param m A matrix of variates 
dnorm_mat <- function(m) {
    .Call('_varapproxr_dnorm_mat', PACKAGE = 'varapproxr', m)
}

#' Perform Jaakkola-Jordan update of variational parameters
#' 
#' @param X The design matrix
#' @param y The response vector
#' @param eta1 The current value of 1st natural parameter
#' @param eta2 The current value of the 2nd natural parameter
#' @param eta1_p The prior value of the 1st natural parameter
#' @param eta2_p The prior value of the 2nd natural parameter
jaakkola_jordan <- function(X, y, eta1, eta2, eta1_p, eta2_p) {
    .Call('_varapproxr_jaakkola_jordan', PACKAGE = 'varapproxr', X, y, eta1, eta2, eta1_p, eta2_p)
}

#' Perform Jaakkola-Jordan update of variational parameters
#' 
#' @param X The design matrix
#' @param y The response vector
#' @param n The trial vector
#' @param eta1 The current value of 1st natural parameter
#' @param eta2 The current value of the 2nd natural parameter
#' @param eta1_p The prior value of the 1st natural parameter
#' @param eta2_p The prior value of the 2nd natural parameter
jaakkola_jordan_n <- function(X, y, n, eta1, eta2, eta1_p, eta2_p) {
    .Call('_varapproxr_jaakkola_jordan_n', PACKAGE = 'varapproxr', X, y, n, eta1, eta2, eta1_p, eta2_p)
}

#' Perform Saul-Jordan update of variational parameters
#' 
#' @param X The design matrix
#' @param y The response vector
#' @param eta1 The current value of 1st natural parameter
#' @param eta2 The current value of the 2nd natural parameter
#' @param eta1_p The prior value of the 1st natural parameter
#' @param eta2_p The prior value of the 2nd natural parameter
#' @param omega1 The current value of the Omega1 variational parameter
saul_jordan <- function(X, y, eta1, eta2, eta1_p, eta2_p, omega1) {
    .Call('_varapproxr_saul_jordan', PACKAGE = 'varapproxr', X, y, eta1, eta2, eta1_p, eta2_p, omega1)
}

#' Perform Saul-Jordan update of variational parameters
#' 
#' @param X The design matrix
#' @param y The response vector
#' @param n The trial vector
#' @param eta1 The current value of 1st natural parameter
#' @param eta2 The current value of the 2nd natural parameter
#' @param eta1_p The prior value of the 1st natural parameter
#' @param eta2_p The prior value of the 2nd natural parameter
#' @param omega1 The current value of the Omega1 variational parameter
saul_jordan_n <- function(X, y, n, eta1, eta2, eta1_p, eta2_p, omega1) {
    .Call('_varapproxr_saul_jordan_n', PACKAGE = 'varapproxr', X, y, n, eta1, eta2, eta1_p, eta2_p, omega1)
}

#' Perform Knowles-Minka-Wand update of variational parameters
#' 
#' @param X The design matrix
#' @param y The response vector
#' @param eta1 The current value of 1st natural parameter
#' @param eta2 The current value of the 2nd natural parameter
#' @param eta1_p The prior value of the 1st natural parameter
#' @param eta2_p The prior value of the 2nd natural parameter
#' @param MS_p The 
#' @param MS_s The
knowles_minka_wand <- function(X, y, eta1, eta2, eta1_p, eta2_p, MS_p, MS_s) {
    .Call('_varapproxr_knowles_minka_wand', PACKAGE = 'varapproxr', X, y, eta1, eta2, eta1_p, eta2_p, MS_p, MS_s)
}

#' Perform Knowles-Minka-Wand update of variational parameters
#' 
#' @param X The design matrix
#' @param y The response vector
#' @param n The trials vector
#' @param eta1 The current value of 1st natural parameter
#' @param eta2 The current value of the 2nd natural parameter
#' @param eta1_p The prior value of the 1st natural parameter
#' @param eta2_p The prior value of the 2nd natural parameter
#' @param MS_p The 
#' @param MS_s The
knowles_minka_wand_n <- function(X, y, n, eta1, eta2, eta1_p, eta2_p, MS_p, MS_s) {
    .Call('_varapproxr_knowles_minka_wand_n', PACKAGE = 'varapproxr', X, y, n, eta1, eta2, eta1_p, eta2_p, MS_p, MS_s)
}

#' Perform variational inference for logistic regression model
#' 
#' @param X The design matrix
#' @param y The response vector
#' @param mu0 The prior mean for beta paramter
#' @param Sigma0 The prior variance for beta parameter
#' @param tol The tolerance level to assess convergence
#' @param maxiter The maximum number of iterations
#' @param maxiter_jj The maximum number of Jaakkola-Jordan iterations to initialise estimation
#' @param alg The algorithm used for final estimation of variational parameters. 
#' Must be one of "jj", "sj", "kmw".
#' 
#' @export
vb_logistic <- function(X, y, mu0, Sigma0, tol = 1e-8, maxiter = 1000L, maxiter_jj = 25L, alg = "jj") {
    .Call('_varapproxr_vb_logistic', PACKAGE = 'varapproxr', X, y, mu0, Sigma0, tol, maxiter, maxiter_jj, alg)
}

#' Perform variational inference for logistic regression model
#' 
#' @param X The design matrix
#' @param y The response vector
#' @param n The trial vector
#' @param mu0 The prior mean for beta paramter
#' @param Sigma0 The prior variance for beta parameter
#' @param tol The tolerance level to assess convergence
#' @param maxiter The maximum number of iterations
#' @param maxiter_jj The maximum number of Jaakkola-Jordan iterations to initialise estimation
#' @param alg The algorithm used for final estimation of variational parameters. 
#' Must be one of "jj", "sj", "kmw".
#' 
#' @export
vb_logistic_n <- function(X, y, n, mu0, Sigma0, tol = 1e-8, maxiter = 1000L, maxiter_jj = 25L, alg = "jj") {
    .Call('_varapproxr_vb_logistic_n', PACKAGE = 'varapproxr', X, y, n, mu0, Sigma0, tol, maxiter, maxiter_jj, alg)
}

#' Return the entropy of multivariate normal density
#' 
#' @param S The covariate matrix
#' @return value The entropy
mvn_entropy <- function(S) {
    .Call('_varapproxr_mvn_entropy', PACKAGE = 'varapproxr', S)
}

#' Normal parametric variational Bayes for Exponential PH Model.
#' 
#' Perform Normal approximation variational inference for 
#' proportional-hazards model with exponential base.
#' 
#' @param X The design matrix
#' @param y The response vector
#' @param v The censoring vector
#' @param mu0 The prior mean for beta
#' @param Sigma0 The prior covariance for beta
#' @param verbose Print trace of the lower bound to console. Default is \code{FALSE}.
#' @return A list containing:
#' \describe{
#'   \item{converged}{Indicator for algorithm convergence.}
#'   \item{elbo}{Vector of the ELBO sequence.} 
#'   \item{mu}{The optimised value of mu.}
#'   \item{Sigma}{The optimised value of Sigma.}
#' }
#' 
#' @useDynLib
#' @export
ph_exponential <- function(X, y, v, mu0, Sigma0, tol = 1e-8, maxiter = 100L, verbose = FALSE) {
    .Call('_varapproxr_ph_exponential', PACKAGE = 'varapproxr', X, y, v, mu0, Sigma0, tol, maxiter, verbose)
}

